### PR TITLE
fix #1926 fix client side configuration does not work in CGroup

### LINKED ISSUE #1926: [CGroup] client side configuration does not work

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

File: daemon/src/test/scala/io/gearpump/cluster/MiniCluster.scala [hunk 1]
```diff
@@ -63,7 +63,7 @@ class MiniCluster {
     val workerListFuture = (master ? GetAllWorkers).asInstanceOf[Future[WorkerList]]
 
     // wait until the worker is registered.
-    val workers = Await.result[WorkerList](workerListFuture, 5 seconds)
+    val workers = Await.result[WorkerList](workerListFuture, 15 seconds)
```
Comment (stanleyxu2005) [inline daemon/src/test/scala/io/gearpump/cluster/MiniCluster.scala]: Can we externalize the const?

Comment (huafengw) [inline daemon/src/test/scala/io/gearpump/cluster/MiniCluster.scala]: Maybe in we can do it in another pr

**Comment by stanleyxu2005** [comment]
+1
