### PR TITLE
fix #1653, fix the dynamic-dag regression

### LINKED ISSUE #1653: failed to replace processor successfully
It's caused by the former refactor of Task and Executor

### LINKED ISSUE #1670: Improve TaskActor by removing stashing messages.

### PR DESCRIPTION
**Pull request by clockfly**

### CODE REVIEW

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 1]
```diff
@@ -148,6 +148,7 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
       tasks.get(registered.taskId).foreach {
         case (actorRef, sessionId) =>
           tasks += registered.taskId -> (actorRef, registered.sessionId)
+          actorRef forward registered
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: Seem like Executor's ```tasks``` don't need to keep sessionId any more

**Comment by clockfly** [comment]
@huafengw 
 fixed.

**Comment by huafengw** [comment]
Compilation failed

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 2]
```diff
@@ -115,8 +115,9 @@ private[appmaster] class TaskManager(
     case Event(TasksLaunched, state) =>
       // We will track all launched task by message RegisterTask
       stay
-    case Event(TasksChanged, state) =>
-      // We will track all changed task by message TaskChanged.
+    case Event(TasksChanged(tasks), state) =>
+      tasks.foreach(task =>state.taskChangeRegistry.taskChanged(task))
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: Should remove  ```case class TaskChanged(taskId: TaskId, dagVersion: Int)```?

Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: I'd like to keep it as it is so that it is easier verify whether this handler work or not in unit test.

**Comment by huafengw** [comment]
TaskManagerSpec and ExecutorSpec failed.

**Comment by clockfly** [comment]
fixed.

**Comment by huafengw** [comment]
+1
