### PR TITLE
 fix #1983, fix KafkaUtilSpec failure 

### LINKED ISSUE #1983: KafkaUtilSpec failure

### PR DESCRIPTION
**Pull request by manuzhang**
Try fixing the random KafkaUtilSpec. Do not merge.

### CODE REVIEW

File: external/kafka/src/test/scala/io/gearpump/streaming/kafka/util/KafkaServerHarness.scala [hunk 1]
```diff
@@ -47,7 +50,13 @@ trait KafkaServerHarness extends ZookeeperHarness {
   def createTopicUntilLeaderIsElected(topic: String, partitions: Int, replicas: Int) = {
     val zkClient = connectZk()
     try {
-      TestUtils.createTopic(zkClient, topic, partitions, replicas, servers)
+      // create topic
+      AdminUtils.createTopic(zkClient, topic, partitions, replicas, new Properties)
+      // wait until the update metadata request for new topic reaches all servers
+      (0 until partitions).map { case i =>
+        TestUtils.waitUntilMetadataIsPropagated(servers, topic, i, timeout = 10000)
```
Comment (stanleyxu2005) [inline external/kafka/src/test/scala/io/gearpump/streaming/kafka/util/KafkaServerHarness.scala]: Can timeout be a optional parameter of `createTopicUntilLeaderIsElected`

**Comment by manuzhang** [comment]
travis shows the change is working

**Comment by huafengw** [comment]
+1
