### PR TITLE
fix #1670, regression, change taskActor back to use stashing.

### LINKED ISSUE #1670: Improve TaskActor by removing stashing messages.

### PR DESCRIPTION
**Pull request by clockfly**

### CODE REVIEW

**Comment by manuzhang** [comment]
This includes previous commits. Please rebase on master head.

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 1]
```diff
@@ -44,12 +44,12 @@ import scala.concurrent.duration._
...
     appId: Int,
     dagManager: ActorRef,
-    subDAGManager: SubDAGManager,
+    jarScheduler: JarScheduler,
     executorManager: ActorRef,
     clockService: ActorRef,
     appMaster: ActorRef,
     appName: String)
-  extends Actor with FSM[State, StateData] {
+  extends Actor {
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: why is `FSM` dropped ? What's the advantage of the other way ?

Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: Several reasons:
1. Equivalent in function, as least this is true for TaskManager.
2. We can have more than one state, like this: dynamicDag(state, recoverState), so that no need to hack the StateData to contain recoverState. 
3. Receive is more easy and composable than StateFunction. 
For example
```
case Event(StartExecutorsTimeOut, state)
```
it is not necessary for every event like StartExecutorsTimeOut to coupled with a state. If I want to reuse this code, then I need to make sure the state points to same type.

4. There is no type in State.
case Event(StartExecutorsTimeOut, state)
I need to cast state to some sub-class to use it. I don't like casting.

**Comment by clockfly** [comment]
@manuzhang 
It is already rebased. It also contains a minor fix to config and log.

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 2]
```diff
@@ -128,181 +227,87 @@ private[appmaster] class TaskManager(
...
+
+        (clockService ? ChangeToNewDAG(state.dag)).map { _ =>
+          executorManager ! BroadCast(StartAllTasks(state.dag.version))
+          context.become(applicationReady(new DagReadyState(state.dag, state.taskRegistry)))
         }
       }
-      sender ! TaskList(taskList)
-      stay
+    case locationRejected: TaskLocationsRejected =>
+      LOG.error(s"received $locationRejected, start to recover")
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: should not be error

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 3]
```diff
@@ -122,109 +131,159 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
+          }
 
-    case startAll@StartAllTasks(taskLocations, startClock, version) =>
-      LOG.info(s"TaskLocations Ready...")
-      assertVersion(dagVersion, version, clue = startAll)
+          val replyTo = sender
+          express.startClients(taskLocations.locations.keySet).foreach { _ =>
+            express.remoteAddressMap.send(result)
+            express.remoteAddressMap.future().foreach { _ =>
+              LOG.error(s"sending TaskLocationsReceived back to " + replyTo)
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: should not be error

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala (hunk 2 above)
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: why?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 4]
```diff
@@ -122,109 +131,159 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
-      s"executor id is $executorId, treat it as MessageLoss"
-    LOG.error(cause)
-    appMaster ! MessageLoss(executorId, taskId, cause)
+  def applicationReady(dagVersion: Int): Receive = {
+    state = State.ACTIVE
+    transitionEnd = System.currentTimeMillis()
+    LOG.info("Transit to state Application Ready. This transition takes " + (transitionEnd - transitionStart) + "milliseconds")
+    box {
+      case start: StartDynamicDag =>
+        LOG.error("received StartDynamicDag")
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: should not be error

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala (hunk 2 above)
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: sorry, comment at the wrong place

**Comment by clockfly** [comment]
fixed.

**Comment by huafengw** [comment]
I'm wondering does TaskActor need to stash message since we have TaskLocationReady check

**Comment by clockfly** [comment]
@huafengw 
Yes, we stil need to do stash, as we want the StartClock to be the first message being processed.

**Comment by clockfly** [comment]
@huafengw 
Now the stashing is no longer a pain, I have done some optimizaiton on stash, please check the code.

**Comment by huafengw** [comment]
+1

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 5]
```diff
@@ -122,109 +131,159 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
 
-  private val timeOutHandler = (taskId: TaskId) => {
-    val cause = s"Failed to register task $taskId to AppMaster of application $appId, " +
-      s"executor id is $executorId, treat it as MessageLoss"
-    LOG.error(cause)
-    appMaster ! MessageLoss(executorId, taskId, cause)
+  def applicationReady(dagVersion: Int): Receive = {
+    state = State.ACTIVE
+    transitionEnd = System.currentTimeMillis()
+    LOG.info("Transit to state Application Ready. This transition takes " + (transitionEnd - transitionStart) + "milliseconds")
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: should not print this on start up. Otherwise, the following log doesn't make sense.

```
Transit to state Application Ready. This transition takes 1450074184253milliseconds
```

Also, please add a space before "milliseconds"

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 6]
```diff
@@ -61,7 +63,14 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
   private val address = ActorUtil.getFullPath(context.system, self.path)
   private val systemConfig = context.system.settings.config
   private val serializerPool = getSerializerPool()
-  private val registerTaskTimeout = systemConfig.getLong(GEARPUMP_STREAMING_REGISTER_TASK_TIMEOUT_MS)
+
+  private var state = State.ACTIVE
+  private var transitionStart = 0L // state transition start, in unix time
+  private var transitionEnd = 0L // state transition end, in unix time
+  private val transitWarningThreshod = 5000 // ms,
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: typo, Threshod -> Threshold

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 7]
```diff
@@ -122,109 +131,159 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
+          express.startClients(taskLocations.locations.keySet).foreach { _ =>
+            express.remoteAddressMap.send(result)
+            express.remoteAddressMap.future().foreach { _ =>
+              LOG.info(s"sending TaskLocationsReceived back to appmaster")
+              replyTo ! TaskLocationsReceived(version, executorId)
+            }
+          }
+          context.become(dynamicDagPhase2(dagVersion, launched, changed))
+        } else {
+          LOG.error("Inconsistence between AppMaser and Executor! AppMaster thinks DynamicDag transition is ready, " +
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: incosistence -> inconsistency

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 8]
```diff
@@ -122,109 +131,159 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
+        context.become(applicationReady(dagVersion))
+    }
   }
 
-  private val timeOutHandler = (taskId: TaskId) => {
-    val cause = s"Failed to register task $taskId to AppMaster of application $appId, " +
-      s"executor id is $executorId, treat it as MessageLoss"
-    LOG.error(cause)
-    appMaster ! MessageLoss(executorId, taskId, cause)
+  def applicationReady(dagVersion: Int): Receive = {
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: `TaskChanged` message from `TaskActor` is ignored.

**Comment by manuzhang** [comment]
why do we send `ChangeTask` message to the `TaskActor` being modified ? It seems nothing is changed here 

```scala
    case ChangeTask(_, dagVersion, life, subscribers) =>
      this.life = life
      subscribers.foreach { subscriber =>
        val processorId = subscriber.processorId
        val subscription = getSubscription(processorId)
        subscription match {
          case Some(subscription) =>
            subscription.changeLife(subscriber.lifeTime cross this.life)
          case None =>
            val subscription = new Subscription(appId, executorId, taskId, subscriber, sessionId, this,
              maxPendingMessageCount, ackOnceEveryMessageCount)
            subscription.start
            subscriptions :+= (subscriber.processorId, subscription)
            // sort, keep the order
            subscriptions = subscriptions.sortBy(_._1)
        }
      }
      sender ! TaskChanged(taskId, dagVersion)
```

**Comment by huafengw** [comment]
```subscriptions ``` is changed

**Comment by manuzhang** [comment]
ok, I see. The `PartitionerDescription` is different.
