### PR TITLE
fix #1777, Dynamic DAG failed after changing parallelism for many times

### LINKED ISSUE #1777: Dynamic DAG failed after changing parallelism for many times
How to reproduce:

Submit SOL through Web UI and continuously changing parallelism SOLStreamProducer from 1 to 2, 3, 4, 5. After 4 or 5 times, SOL will fail itself.

executor log:

```
[INFO] [12/25/2015 08:57:12.019] [Slf4jLogger] Slf4jLogger started
[INFO] [12/25/2015 08:57:12.078] [Remoting] Starting remoting
[INFO] [12/25/2015 08:57:12.257] [Remoting] Remoting started; listening on addresses :[akka.tcp://app1system9@127.0.0.1:53216]
[INFO] [12/25/2015 08:57:12.297] [Metrics$] Metrics is enabled...,  true
[INFO] [12/25/2015 08:57:12.302] [Daemon@app1system9] RegisterActorSystem to akka.tcp://app1-executor-1@127.0.0.1:59046/user/daemon/appdaemon1/$b/$a/$o, current user: manu
[WARN] [12/25/2015 08:57:12.417] [ReliableDeliverySupervisor] Association with remote system [akka.tcp://app1-executor-1@127.0.0.1:59046] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://app1-executor-1@127.0.0.1:59046]] Caused by: [Connection refused: /127.0.0.1:59046]
[ERROR] [12/25/2015 08:57:37.317] [Daemon@app1system9] RegisterActorSystemFailed
java.util.concurrent.TimeoutException
        at io.gearpump.util.ActorSystemBooter$Daemon.<init>(ActorSystemBooter.scala:108)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[INFO] [12/25/2015 08:57:37.320] [Daemon@app1system9] ActorSystem app1system9 is shutting down...
[INFO] [12/25/2015 08:57:37.332] [RemoteActorRefProvider$RemotingTerminator] Shutting down remote daemon.
[INFO] [12/25/2015 08:57:37.334] [RemoteActorRefProvider$RemotingTerminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [12/25/2015 08:57:37.391] [RemoteActorRefProvider$RemotingTerminator] Remoting shut down.
[INFO] [12/25/2015 08:57:37.407] [ActorSystemBooter$] Maybe we have received a SIGINT signal from parent process, start to cleanup resources...
```

application master log:

```
[INFO] [12/25/2015 08:56:56.277] [ExecutorSystemLauncher] Launching Executor ...appId: 1, executorSystemId: 8, slots: 2 on worker WorkerInfo(0,Actor[akka.tcp://master@127.0.0.1:3000/user/Worker1#-1056887906])
[INFO] [12/25/2015 08:56:56.278] [ExecutorSystemLauncher] Launching Executor ...appId: 1, executorSystemId: 9, slots: 3 on worker WorkerInfo(1,Actor[akka.tcp://master@127.0.0.1:3000/user/Worker0#-1162316881])
[ERROR] [12/25/2015 08:57:11.278] [ExecutorSystemLauncher] The Executor ActorSystem 8 has not been started in time
[ERROR] [12/25/2015 08:57:11.279] [ExecutorSystemScheduler@app1] Failed to launch executor system for Actor[akka://app1-executor-1/user/daemon/appdaemon1/$c/appmaster/executors#-1755639163] due to timeout
[ERROR] [12/25/2015 08:57:11.279] [AppMaster@app1] Failed to allocate resource in time, shutdown application 1
[ERROR] [12/25/2015 08:57:11.285] [ExecutorSystemLauncher] The Executor ActorSystem 9 has not been started in time
[ERROR] [12/25/2015 08:57:11.285] [ExecutorSystemScheduler@app1] Failed to launch executor system for Actor[akka://app1-executor-1/user/daemon/appdaemon1/$c/appmaster/executors#-1755639163] due to timeout
[INFO] [12/25/2015 08:57:11.505] [ActorSystemBooter$] Maybe we have received a SIGINT signal from parent process, start to cleanup resources....
```

### PR DESCRIPTION
**Pull request by clockfly**

### CODE REVIEW

**Comment by clockfly** [comment]
Not ready for merge.

File: streaming/src/main/scala/io/gearpump/streaming/task/TaskActor.scala [hunk 1]
```diff
@@ -242,11 +242,21 @@ class TaskActor(
...
       this.upstreamMinClock = upstreamClock
-      val update = UpdateClock(taskId, minClock)
+      val latestMinClock = minClock
+      val update = UpdateClock(taskId, latestMinClock)
       context.system.scheduler.scheduleOnce(CLOCK_REPORT_INTERVAL) {
         appMaster ! update
       }
 
+      // check whether current task is dead.
+      if (latestMinClock > life.death) {
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/task/TaskActor.scala]: why reports `UpdateClock` if the task is already dead ?

Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/task/TaskActor.scala]: When sending unRegister, it is not actually dead. 
It will only be dead when the AppMaster send back a StopTask.

During this transition time, we still need the clock to progress.

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/ClockService.scala [hunk 2]
```diff
@@ -76,31 +78,87 @@ class ClockService(dag : DAG, store: AppDataStore) extends Actor with Stash {
...
-  private var checkpointClocks = Map.empty[TaskId, Vector[TimeStamp]]
+  private var checkpointClocks: Map[TaskId, Vector[TimeStamp]] = null
+
   private var minCheckpointClock: Option[TimeStamp] = None
 
-  private def setDAG(dag: DAG, startClock: TimeStamp): Unit = {
-    val newClocks = dag.processors.map { pair =>
+  private def checkpointEnabled(processor: ProcessorDescription): Boolean = {
+    val taskConf = processor.taskConf
+    if (taskConf != null && taskConf.getBoolean("state.checkpoint.enable") == Some(true)) {
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/ClockService.scala]: just return the test evaluation?

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/JarScheduler.scala [hunk 3]
```diff
@@ -32,43 +36,105 @@ import io.gearpump.util.Graph
...
-      val (jar, processors) = jarAndProcessors
-      //Construct the sub DAG
-      val graph = Graph.empty[ProcessorDescription, PartitionerDescription]
-      processors.foreach(graph.addVertex)
-      val subDag = DAG(graph)
-      val taskScheduler = taskSchedulers.getOrElse(jar, new TaskSchedulerImpl(appId, appName, config))
-      taskScheduler.setDAG(subDag)
-      jar -> taskScheduler
+class JarScheduler(appId : Int, appName: String, config: Config, factory: ActorRefFactory) {
+  private val actor: ActorRef = factory.actorOf(Props(new JarSchedulerImpl(appId, appName, config)))
```
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/JarScheduler.scala]: Why change JarScheduler to actor-implementation?

Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/JarScheduler.scala]: We need to use StartTime to filter out dead processors. But the startTime is not ready when we call setDAG. 

So we need to use Actor message stashing to reorder message, so that we get a StartClock before doing task scheduling.

Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/JarScheduler.scala]: Is it possible in TaskManager's LatestDag handler,
```
startClock.map { clock =>
  jarScheduler.setDag(dag, clock)
  jarScheduler.getResourceRequests
}
```

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/ClockService.scala (hunk 2 above)
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/ClockService.scala]: ok

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/JarScheduler.scala (hunk 3 above)
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/JarScheduler.scala]: It is not OK. there are other calls to jarScheduler.xxmethod in TaskManager. Since map execute in a future, we cannot gurantee setDag is executed before  .xxmethod

**Comment by huafengw** [comment]
+1

File: streaming/src/test/scala/io/gearpump/streaming/appmaster/AppMasterSpec.scala [hunk 4]
```diff
@@ -93,8 +93,11 @@ class AppMasterSpec extends WordSpec with Matchers with BeforeAndAfterEach with
     mockMaster.reply(AppMasterRegistered(appId))
     mockMaster.expectMsg(15 seconds, GetAppData(appId, "DAG"))
     mockMaster.reply(GetAppDataResult("DAG", null))
-    mockMaster.expectMsgAllOf(15 seconds, GetAppData(appId, "startClock"), RequestResource(appId, ResourceRequest(Resource(4))))
+    mockMaster.expectMsg(15 seconds, GetAppData(appId, "startClock"))
```
Comment (manuzhang) [inline streaming/src/test/scala/io/gearpump/streaming/appmaster/AppMasterSpec.scala]: Will this cause UT failure ? I remember UT failed previously because `ResourceRequest` is received before `GetAppData`.

Comment (clockfly) [inline streaming/src/test/scala/io/gearpump/streaming/appmaster/AppMasterSpec.scala]: Hi, this is solved.

Comment (clockfly) [inline streaming/src/test/scala/io/gearpump/streaming/appmaster/AppMasterSpec.scala]: Now, ResourceRequest can only be triggered after GetStartTime.
