### PR TITLE
fix #1609, fix storm message timestamp bugs

### LINKED ISSUE #1609: storm over gearpump drops first message

### PR DESCRIPTION
**Pull request by manuzhang**
[Review on Reviewable](https://reviewable.io/reviews/gearpump/gearpump/1610)

### CODE REVIEW

**Comment by manuzhang** [comment]
1. The bug is caused by that timestamp is set after the message is emitted. Hence, the first message gets and timestamp -1 and is filtered out. 
2. This PR also fixes that seconds and milliseconds are mixed up in several places

**Comment by manuzhang** [comment]
please hold the merge. I've got to fix the tests

**Comment by clockfly** [comment]
+1 on the patch.

One question about the checkpoint clock, why bolt need to report checkpoint clock?

Cannot the spout just query the AppMaster to get the latest clock? So that it know whether to ack or fail?

File: experiments/storm/src/main/scala/io/gearpump/experiments/storm/producer/StormProducer.scala [hunk 1]
```diff
@@ -79,11 +79,11 @@ private[storm] class StormProducer(gearpumpSpout: GearpumpSpout,
...
   def getCheckpointClock: Unit = {
-    taskContext.scheduleOnce(Duration(StormConstants.CHECKPOINT_INTERVAL_SECS,
-      TimeUnit.SECONDS))(taskContext.appMaster ! GetCheckpointClock)
+    taskContext.scheduleOnce(Duration(StormConstants.CHECKPOINT_INTERVAL_MILLIS,
+      TimeUnit.MILLISECONDS))(taskContext.appMaster ! GetCheckpointClock)
   }
 
-  private def scheduleTimeout(timeout: Int): Unit = {
-    taskContext.scheduleOnce(Duration(timeout, TimeUnit.SECONDS)){ self ! TIMEOUT }
+  private def scheduleTimeout(timeout: Long): Unit = {
```
Comment (stanleyxu2005) [inline experiments/storm/src/main/scala/io/gearpump/experiments/storm/producer/StormProducer.scala]: You might use `duration` to avoid potential unit confusion

Comment (manuzhang) [inline experiments/storm/src/main/scala/io/gearpump/experiments/storm/producer/StormProducer.scala]: Long is more convenient as long as I use it consistently and make good names

**Comment by manuzhang** [comment]
@clockfly AppMaster doesn't know whether Bolts have successfully executed tuples unless received report clock from bolts on `bolt.ack`

**Comment by manuzhang** [comment]
@clockfly merge this in. We can continue the discussion on new issues or offline.
