### PR TITLE
fix #1485 no more pending messages in ExpressTransport

### LINKED ISSUE #1485: NoSuchElementException when flushing pending messages
This is only caused by another Exception from another Task. For example,

If TaskA throws an Exception, Executors will clean up their `remoteAddressMap`s and send `PoisonPill` to all its tasks. It's possible that, before receiving the `PoisonPill`, TaskB just receives `TaskLocationReady` and invokes `SendLater.sendPendingMessages`. Since the `remoteAddressMap` is already cleaned, the a `NoSuchElementException` would be thrown by TaskB.

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

File: streaming/src/main/scala/io/gearpump/streaming/task/TaskActor.scala [hunk 1]
```diff
@@ -281,6 +259,7 @@ class TaskActor(
         queue.add(msg)
         handler()
       case None =>
+        LOG.error(s"Task $taskId drop message $msg")
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/task/TaskActor.scala]: There is one problem, when there is a upstream zombie task keeping sending message, it will flood the log file. 

Maybe we should find some solution which meet:
1. indicate there is unexpected error happening.
2. avoid flooding the log file.

File: streaming/src/main/scala/io/gearpump/streaming/task/ExpressTransport.scala [hunk 2]
```diff
@@ -67,63 +60,11 @@ trait ExpressTransport {
 
         val remoteAddress = express.lookupRemoteAddress(transportId)
         if (remoteAddress.isDefined) {
-          if(sendLater.hasPendingMessages){
-            sendLater.flushPendingMessages(remoteAddress.get, transportId)
-          }
           express.transport(taskMessage, remoteAddress.get)
         } else {
-          sendLater.addMessage(transportId, taskMessage)
+          LOG.error(s"Can not find target task $remote")
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/task/ExpressTransport.scala]: Maybe you want to put some inline document about on what ocassion this error will happen?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 3]
```diff
@@ -179,11 +187,28 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
+      tasks.get(rejected.taskId).foreach(_ ! PoisonPill)
+  }
+
+  def taskMsgHandler: Receive = {
+    case register: RegisterTask =>
+      sendMsgWithTimeOutCallBack(appMaster, register, registerTaskTimout, registerTaskTimeOut())
+  }
+
+  private def registerTaskTimeOut(): Unit = {
+    LOG.error(s"Failed to register task to AppMaster of application $appId, executor id is $executorId")
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: How can we know which task trigger the timeout error?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 4]
```diff
@@ -179,11 +187,28 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
 
     case query: QueryExecutorConfig =>
       sender ! ExecutorConfig(systemConfig)
+
+    case registered: TaskRegistered =>
+      LOG.debug(s"Register task ${registered.taskId} succeed")
+    case rejected: TaskRejected =>
+      LOG.info(s"Task ${rejected.taskId} is rejected by AppMaster, shutting down myself...")
+      tasks.get(rejected.taskId).foreach(_ ! PoisonPill)
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: Should we clean out the reference in field "tasks"?

As executor has watched the task, if task is killed by PoisonPill, executor will restart it automatically.

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala (hunk 3 above)
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: What else do we need to do to recover from failure besides logging?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 5]
```diff
@@ -179,11 +187,28 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
 
     case query: QueryExecutorConfig =>
       sender ! ExecutorConfig(systemConfig)
+
+    case registered: TaskRegistered =>
+      LOG.debug(s"Register task ${registered.taskId} succeed")
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: Is this log important? Do we need to make it a INFO level?

What if some TaskRegistered  message is lost ,will there be some problem?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 6]
```diff
@@ -147,11 +152,14 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
-        express.remoteAddressMap.send(result)
-        express.remoteAddressMap.future().map{_ =>
-          tasks.foreach { task =>
-            task._2 ! TaskLocationReady
+      getStartClock.map { startClock =>
+        express.startClients(locations.keySet).map { _ =>
+          express.remoteAddressMap.send(result)
+          express.remoteAddressMap.future().map { _ =>
+            tasks.foreach { task =>
+              val sessionId = ids.newSessionId
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: Is ids.newSessionId thread safe?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 7]
```diff
@@ -147,11 +152,14 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
         val (host, taskIdList) = kv
         taskIdList.map(taskId => (TaskId.toLong(taskId), host))
       }
-      express.startClients(locations.keySet).map { _ =>
-        express.remoteAddressMap.send(result)
-        express.remoteAddressMap.future().map{_ =>
-          tasks.foreach { task =>
-            task._2 ! TaskLocationReady
+      getStartClock.map { startClock =>
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: Should the start clock be passed along with TaskLocations?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 8]
```diff
@@ -57,10 +60,12 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
 
   private val LOG: Logger = LogUtil.getLogger(getClass, executor = executorId, app = appId)
 
+  implicit val timeOut = FUTURE_TIMEOUT
   private val address = ActorUtil.getFullPath(context.system, self.path)
-  val systemConfig = context.system.settings.config
-
+  private val systemConfig = context.system.settings.config
+  private val ids = new SessionIdFactory(executorId)
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: How to gurantee that the session id will not have duplicated value?

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 9]
```diff
@@ -98,6 +85,7 @@ private[appmaster] class TaskManager(
         val resourceRequestDetail = subDAGManager.executorFailed(executorId)
         executorManager ! StartExecutors(resourceRequestDetail.requests, resourceRequestDetail.jar)
       } else {
+        appMaster ! ShutdownApplication(appId)
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: instead of telling AppMaster to shutdown, maybe it is better to tell AppMaster what is going wrong. It is AppMaster's responsibility to decide how to react to that error.

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 10]
```diff
@@ -215,9 +200,12 @@ private[appmaster] class TaskManager(
       }
 
     case Event(MessageLoss(executorId, cause), state) =>
-      if (state.taskRegistry.isTaskRegisteredForExecutor(executorId)) {
+      if (state.taskRegistry.isTaskRegisteredForExecutor(executorId) &&
+            executorRestartPolicy.allowRestartExecutor(executorId)) {
         goto(Recovery) using state.recoverState
       } else {
+        LOG.error(s"Task fails too many times to recover, shut down the application")
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: Better need to document which task is restarting too many times...

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 11]
```diff
@@ -179,11 +187,28 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
+      LOG.info(s"Task ${rejected.taskId} is rejected by AppMaster, shutting down myself...")
+      tasks.get(rejected.taskId).foreach(_ ! PoisonPill)
+  }
+
+  def taskMsgHandler: Receive = {
+    case register: RegisterTask =>
+      sendMsgWithTimeOutCallBack(appMaster, register, registerTaskTimout, registerTaskTimeOut())
+  }
+
+  private def registerTaskTimeOut(): Unit = {
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: better name the function to timeOutBack to differentiate it from the val `registerTaskTimout`

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 12]
```diff
@@ -57,10 +60,12 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
...
   private val LOG: Logger = LogUtil.getLogger(getClass, executor = executorId, app = appId)
 
+  implicit val timeOut = FUTURE_TIMEOUT
   private val address = ActorUtil.getFullPath(context.system, self.path)
-  val systemConfig = context.system.settings.config
-
+  private val systemConfig = context.system.settings.config
+  private val ids = new SessionIdFactory(executorId)
   private val serializerPool = getSerializerPool()
+  private val registerTaskTimout = systemConfig.getLong(GEARPUMP_STREAMING_REGISTER_TASK_TIMEOUT_MS)
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: typo `Timout`

File: streaming/src/main/scala/io/gearpump/streaming/task/ExpressTransport.scala (hunk 2 above)
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/task/ExpressTransport.scala]: what if an unexpected case causing the error to happen ? How about throwing exception here ?

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 13]
```diff
@@ -260,6 +248,8 @@ private[appmaster] class TaskManager(
       }
   }
 
+  when(Recovery)(startTasks orElse ignoreClockEvent)
```
Comment (manuzhang) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: `TaskRegistry` is not cleared if we accept `RegisterTask` on recovery

**Comment by clockfly** [comment]
Also need to consider the case of "at most once".

If user only need "at most once", then we should avoiding rebooting the whole app. 
For example, A -> B, A  -> C (A send data to B)
In  scenario of at most once, when B stops,  we don't want A to be rebooted, as C is still there.

File: streaming/src/main/scala/io/gearpump/streaming/task/ExpressTransport.scala (hunk 2 above)
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/task/ExpressTransport.scala]: I think this error will eventually cause the MessageLoss exception

**Comment by clockfly** [comment]
Do you want to look at the UT failure?

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/ExecutorManager.scala [hunk 14]
```diff
@@ -70,6 +72,11 @@ private[appmaster] class ExecutorManager(
       context.become(service orElse terminationWatch)
   }
 
+  override val supervisorStrategy = OneForOneStrategy(maxNrOfRetries = 10, withinTimeRange = 1 minute) {
+    case ex: Throwable =>
+      Stop
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/ExecutorManager.scala]: We need to LOG this

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala [hunk 15]
```diff
@@ -362,4 +361,8 @@ private [appmaster] object TaskManager {
       sessionId
     }
   }
+}
+
+object Test extends App {
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: Remove test code?

File: streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala [hunk 16]
```diff
@@ -179,11 +175,31 @@ class Executor(executorContext: ExecutorContext, userConf : UserConfig, launcher
 
     case query: QueryExecutorConfig =>
       sender ! ExecutorConfig(systemConfig)
+
+    case registered: TaskRegistered =>
+      taskToSessionId += registered.taskId -> registered.sessionId
+    case rejected: TaskRejected =>
+      tasks.get(rejected.taskId).foreach(_ ! PoisonPill)
```
Comment (clockfly) [inline streaming/src/main/scala/io/gearpump/streaming/executor/Executor.scala]: Do we want to combine taskToSessionId  with tasks, so that it is easier to manage consistency

File: streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala (hunk 13 above)
Comment (huafengw) [inline streaming/src/main/scala/io/gearpump/streaming/appmaster/TaskManager.scala]: When recovery, I think it's using the recovery state, whose TaskRegistry is empty.

**Comment by clockfly** [comment]
@huafeng,

please check
1. whether supervisorStrategy will use the main inbox.
2. check the executor state machine to make sure nothing goes wrong.

**Comment by huafengw** [comment]
@clockfly updated

**Comment by clockfly** [comment]
+1
